export const INTMAX402_ERROR_CODES = {
  // 認証系
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  NONCE_EXPIRED: 'NONCE_EXPIRED',
  NONCE_ALREADY_USED: 'NONCE_ALREADY_USED',
  MISSING_AUTH_HEADER: 'MISSING_AUTH_HEADER',
  INVALID_AUTH_FORMAT: 'INVALID_AUTH_FORMAT',
  // 支払い系
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_RECIPIENT_MISMATCH: 'PAYMENT_RECIPIENT_MISMATCH',
  // ネットワーク系
  INTMAX_NETWORK_UNAVAILABLE: 'INTMAX_NETWORK_UNAVAILABLE',
  INTMAX_SYNC_TIMEOUT: 'INTMAX_SYNC_TIMEOUT',
  INTMAX_BROADCAST_FAILED: 'INTMAX_BROADCAST_FAILED',
  // 設定系
  INVALID_CONFIG: 'INVALID_CONFIG',
  MISSING_PRIVATE_KEY: 'MISSING_PRIVATE_KEY',
} as const;

export type INTMAX402ErrorCode = typeof INTMAX402_ERROR_CODES[keyof typeof INTMAX402_ERROR_CODES];

export class INTMAX402Error extends Error {
  constructor(
    public readonly code: INTMAX402ErrorCode,
    message: string,
    public readonly details?: unknown
  ) {
    super(message);
    this.name = 'INTMAX402Error';
  }
}
